<!DOCTYPE html>
<html lang="en">
<head>
    @include('dashboard.template.top')
    <style>
    </style>
</head>
<body class="bg-gray-600">

    <div class="md:grid grid-cols-5 gap-2 w-11/12 mx-auto my-12 rounded-lg bg-white">

        <!-- section for header and content -->
        <div class="col-span-5 w-full bg-gray-100 rounded-r-lg">
            <!-- header display -->
            @include('dashboard.template.header') 
        </div>

        <!-- display section -->
        <div class="col-span-5 lg:col-span-4 bg-gray-100 shadow-inner border-r-2 border-white h-auto py-14 flex align-middle items-center text-center justify-center rounded-r-md">
            <img id="map_image" src="{{ url($data['site_map']) }}" alt="" class="w-11/12 h-auto mx-auto" usemap="#image-map" onload="set_coordinates()">

            <!-- Image Map Generated by http://www.image-map.net/ -->

            <map name="image-map" id="image_map">
                <area target="" alt="Block1" title="Block1" href="" coords="128,187,475,424" shape="rect" class=" inline-block bg-gray-200 bg-opacity-30 hover:bg-opacity-5">
                <area target="" alt="Block2" title="Block2" href="" coords="482,191,815,427" shape="rect" class=" inline-block bg-gray-200 bg-opacity-30 hover:bg-opacity-5">
                <area target="" alt="Block3" title="Block3" href="" coords="815,193,1148,424" shape="rect" class=" inline-block bg-gray-200 bg-opacity-30 hover:bg-opacity-5">
                <area target="" alt="Block4" title="Block4" href="" coords="130,427,473,644" shape="rect" class=" inline-block bg-gray-200 bg-opacity-30 hover:bg-opacity-5">
                <area target="" alt="Block5" title="Block5" href="" coords="482,429,815,644" shape="rect" class=" inline-block bg-gray-200 bg-opacity-30 hover:bg-opacity-5">
                <area target="" alt="Block6" title="Block6" href="" coords="815,427,1150,644" shape="rect" class=" inline-block bg-gray-200 bg-opacity-30 hover:bg-opacity-5">
            </map>

        </div>
        <div class=" justify-center col-span-5 lg:col-span-1">
            @for ($i = 0; $i < 24; $i++)
                <div class="h-14 w-12 bg-green-400 mx-auto inline-block" ></div>
            @endfor
            <div class="w-full justify-end text-right py-4">
                <div class=" bg-blue-900 px-1 py-1 rounded-full flex max-w-min"><button class="px-3 py-1 border-2 border-blue-900 bg-blue-600 text-4xl text-white rounded-full inline-flex" onclick="add_area()">+</button><span class="text-xl pl-1 pr-3 py-2 text-white inline-flex">section</span></div>
            </div>
        </div>
        <div class="w-11/12 mx-auto col-span-5">
            <a href="https://www.image-map.net" target="_blanc" class="border-2 border-blue-900 rounded bg-gray-100 text-blue-900 py-2 px-3 my-2">Generate code</a>
            <textarea name="map_code" id="map_code" rows="5" class="w-full shadow-inner my-2 pl-3 pr-2 py-2" placeholder="Map code" onchange="load_map()"></textarea>
        </div>
        <div class="invisible w-11/12 col-span-5 flex flex-wrap justify-center border-separate py-2 px-3 bg-gray-50">
            <div class=" w-min py-2 px-2 inline-block shadow-inner">
                <label for="shape" class="text-sm text-green-500 block">shape:</label>
                <select name="shape" id="" class="bg-white text-lg border-b-2 border-blue-900">
                    <option value="rect" selected>rect</option>
                    <option value="circle">circle</option>
                    <option value="poly">poly</option>
                </select>
            </div>    
            <div class=" w-min py-2 px-2 inline-block shadow-inner">
                <label for="label" class="text-sm text-green-500 block">Title:</label>
                <input type="text" class="border-b-2 border-blue-900">
            </div>
            <div class=" w-min py-2 px-2 inline-block shadow-inner">
                <label for="label" class="text-sm text-green-500 block">coords:</label>
                <input type="text" class="border-b-2 border-blue-900">
            </div>
        </div>
    </div>

    <!-- footer view -->
    @include('dashboard.template.footer')
    <script>
        let map_image = document.querySelector("#map_image");
        let coords = [], r_width = 0, r_height = 0;
        let map_code = document.querySelector("#map_code");
        let image_map = document.querySelector("#image_map");

        function set_coordinates() {
            r_width = map_image.width/map_image.naturalWidth;
            r_height = map_image.height/map_image.naturalHeight;
        }
        function load_map() {
        }

    </script>
</body>
</html>